config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get    'register' => 'devise/registrations#new'
    get    'login'    => 'devise/sessions#new'
    get    'profile'  => 'devise/registrations#edit'
    delete 'logout'   => 'devise/sessions#destroy'
  end

  devise_for :users
  authenticated :user do
    root :to => 'dashboard#index'
  end

  resources :contacts, :notifications, :topics, :events, :subscribe

  # API routes
  scope 'api', as: 'api', defaults: {format: :json} do
    match 'contacts',    to: 'api#contact',     via: :post
    match 'topics',      to: 'api#topics',      via: :get
    match 'events',      to: 'api#events',      via: :get
    # Contact subscribe/unsubscribe for topics
    match 'subscribe',   to: 'api#subscribe',   via: :post
    match 'unsubscribe', to: 'api#unsubscribe', via: :post
  end

  match 'contact', as: 'static_contact', to: 'pages#contact', via: :get
  match 'about',   as: 'static_about',   to: 'pages#about',   via: :get

  root :to => 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_and_belongs_to_many :contacts
  before_save :send_notification

  validates :text, presence: true
  
  private
    def send_notification
      # if self.topic.contacts
      #   registration_ids = [] # an array of one or more client registration tokens
      #   self.topic.contacts.each do |contact|
      #     registration_ids.push(contact.token)
      #     self.contacts << contact
      #   end

      #   fcm = FCM.new(self.user.token, verify: false)
      #   # you can set option parameters in here
      #   #  - all options are pass to HTTParty method arguments
      #   #  - ref: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L29-L60
      #   #  fcm = FCM.new("my_api_key", timeout: 3)

      #   options = {notification: {title: self.title, body: self.text, sound: 'default'}, priority: 'high'}
      #   self.response = fcm.send_with_notification_key("topic_#{self.topic_id}", options)[:body]
      # end

      fcm = FCM.new(self.user.token, verify: false)
      options = {notification: {title: self.title, body: self.text, sound: 'default'}, priority: 'high'}
      self.response = fcm.send_with_notification_key("/topics/topic_#{self.topic_id}", options)[:body]
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications
  end

  def new
    @notification = current_user.notifications.build
  end

  def create
    @notification = current_user.notifications.build(notification_params)
    if @notification.save
      redirect_to edit_notification_path(@notification), notice: 'Уведомление успешно создано'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @notification.update(notification_params)
      redirect_to edit_notification_path(@notification), notice: 'Уведомление успешно изменено'
    else
      render :edit
    end
  end

  def destroy
    @notification.delete
    redirect_to :back, notice: 'Уведомление успешно удалено'
  end

  private
    def set_notification
      @notification = Notification.find(params[:id])
    end

    def notification_params
      params.require(:notification).permit(:topic_id, :title, :link, :text)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.haml
= form_for(notification, html: { class: 'row' }) do |f|
  - if notification.errors.any?
    .error_explanation
      %h4= pluralize(notification.errors.count, 'error') + 'prohibited this notification from being saved:'
      %ul
        - notification.errors.full_messages.each do |message|
          %li= message

  .input-field.col.s12
    = f.text_field :title
    = f.label :title, 'Заголовок'
  .input-field.col.l6.m12
    = f.select(:topic_id) do
      - Topic.all.each do |t|
        = content_tag(:option, t.title, value: t.id)
    = f.label :topic, 'Тема'
  .input-field.col.l6.m12
    = f.text_field :link
    = f.label :link, 'Ссылка'
  .input-field.col.s12
    = f.text_area :text, class: 'materialize-textarea'
    = f.label :text, 'Текст'
  .input-field.col.s12
    = f.text_area :response, class: 'materialize-textarea', disabled: 'disabled'
    = f.label :response
  .input-field.col.s12
    = f.submit 'Сохранить', class: 'btn orange'
    = link_to 'Назад', :back, class: 'btn'

app/views/notifications/_grid.html.haml
= link_to icon('plus'), new_notification_path, class: 'btn-floating btn-large waves-effect waves-light right red', style: 'margin-top: -50px'
- if notifications.empty?
  %p У Вас еще нет созданных уведомлений.
- else
  %table.striped
    %thead
      %tr
        %th Заголовок
        %th Тема
        %th Ссылка
    %tbody
      - notifications.each do |n|
        %tr
          %td= n.title
          %td= n.topic.title
          %td= n.link
          %td.right
            = link_to icon('pencil'), edit_notification_path(n), class: 'btn orange'
            = link_to icon('trash-o'), n, class: 'btn red', method: :delete

app/views/notifications/edit.html.haml
.section.light-blue{ style: 'min-height: 240px' }

.container{ style: 'margin-top: -150px' }
  .row
    = render 'dashboard/menu'
    .col.s12.m8.l9
      %nav{ style: 'margin-top: 0.5rem' }
        .nav-wrapper
          .col.s12
            = link_to icon('home'), root_path, class: 'breadcrumb'
            = link_to 'Уведомления', notifications_path, class: 'breadcrumb'
            = link_to 'Редактирование', new_notification_path, class: 'breadcrumb'
      .card-panel
        = render 'form', notification: @notification

app/views/notifications/index.html.haml
.section.light-blue{ style: 'min-height: 240px' }

.container{ style: 'margin-top: -150px' }
  .row
    = render 'dashboard/menu'
    .col.s12.m8.l9
      %nav{ style: 'margin-top: 0.5rem' }
        .nav-wrapper
          .col.s12
            = link_to icon('home'), root_path, class: 'breadcrumb'
            = link_to 'Уведомления', notifications_path, class: 'breadcrumb'
      .card-panel
        = render 'notifications/grid', notifications: @notifications

app/views/notifications/new.html.haml
.section.light-blue{ style: 'min-height: 240px' }

.container{ style: 'margin-top: -150px' }
  .row
    = render 'dashboard/menu'
    .col.s12.m8.l9
      %nav{ style: 'margin-top: 0.5rem' }
        .nav-wrapper
          .col.s12
            = link_to icon('home'), root_path, class: 'breadcrumb'
            = link_to 'Уведомления', notifications_path, class: 'breadcrumb'
            = link_to 'Добавление', new_notification_path, class: 'breadcrumb'
      .card-panel
        = render 'form', notification: @notification