config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get    'register' => 'devise/registrations#new'
    get    'login'    => 'devise/sessions#new'
    get    'profile'  => 'devise/registrations#edit'
    delete 'logout'   => 'devise/sessions#destroy'
  end

  devise_for :users
  authenticated :user do
    root :to => 'dashboard#index'
  end

  resources :contacts, :notifications, :topics, :events, :subscribe

  # API routes
  scope 'api', as: 'api', defaults: {format: :json} do
    match 'contacts',    to: 'api#contact',     via: :post
    match 'topics',      to: 'api#topics',      via: :get
    match 'events',      to: 'api#events',      via: :get
    # Contact subscribe/unsubscribe for topics
    match 'subscribe',   to: 'api#subscribe',   via: :post
    match 'unsubscribe', to: 'api#unsubscribe', via: :post
  end

  match 'contact', as: 'static_contact', to: 'pages#contact', via: :get
  match 'about',   as: 'static_about',   to: 'pages#about',   via: :get

  root :to => 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :notifications
  has_and_belongs_to_many :topics
  has_many :subscribes

  before_validation :set_contact_code

  validates :name,  presence: true
  validates :phone, presence: true, uniqueness: true
  validates :token, presence: true, uniqueness: true
  validates :code,  presence: true, uniqueness: true, length: { minimum: 9, maximum: 9 }

  private
    def set_contact_code
      if self.code.blank?
        self.code = rand 100000000...999999999
      end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @contact = current_user.contacts.build
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      redirect_to edit_contact_path(@contact), notice: 'Контакт успешно создан'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to edit_contact_path(@contact), notice: 'Контакт успешно изменен'
    else
      render :edit
    end
  end

  def destroy
    @contact.delete
    redirect_to :back, notice: 'Контакт успешно удален'
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :phone, :token)
    end

    def check_user
      if @contact.user_id != current_user.id
        respond_to json: {error: true, message: 'Не достаточно прав на изменение Контакта' }
      end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.haml
= form_for contact, html: { class: 'row' } do |f|
  - if contact.errors.any?
    .error_explanation
      %h4= pluralize contact.errors.count, 'error' + 'prohibited this contact from being saved:'
      %ul
        - contact.errors.full_messages.each do |message|
          %li= message

  .input-field.col.l6.s12
    = f.text_field :name
    = f.label :name, 'Имя'
  .input-field.col.l6.s12
    = f.text_field :phone
    = f.label :phone, 'Телефон'
  .input-field.col.l6.s12
    = f.text_field :token
    = f.label :token
  .input-field.col.l6.s12
    = f.text_field :code, disabled: 'disabled'
    = f.label :code

  .input-field.col.s12
    = f.submit 'Сохранить', class: 'btn orange'
    = link_to 'Назад', :back, class: 'btn'

app/views/contacts/_grid.html.haml
= link_to icon('plus'), new_contact_path, class: 'btn-floating btn-large waves-effect waves-light right red', style: 'margin-top: -50px'
- if contacts.empty?
  %p У Вас еще нет созданных контактов.
- else
  %table.striped
    %thead
      %tr
        %th Имя
        %th Телефон
        %th Код
    %tbody
      - contacts.each do |c|
        %tr
          %td= c.name
          %td= c.phone
          %td= c.code
          %td.right
            = link_to icon('pencil'), edit_contact_path(c), class: 'btn orange'
            = link_to icon('trash-o'), contact_path(c), class: 'btn red', method: :delete, data: { confirm: 'Вы уверены?' }

app/views/contacts/edit.html.haml
.section.light-blue{ style: 'min-height: 240px'}

.container{ style: 'margin-top: -150px'}
  .row
    = render('dashboard/menu')
    .col.s12.m8.l9
      %nav{style: 'margin-top: 0.5rem'}
        .nav-wrapper
          .col.s12
            = link_to icon('home'), root_path, class: 'breadcrumb'
            = link_to 'Контакты', contacts_path, class: 'breadcrumb'
            = link_to 'Редактирование', edit_contact_path(@contact), class: 'breadcrumb'

      .card-panel
        = render 'form', contact: @contact

      .col.s12
        %ul.tabs
          %li.tab.col.s6
            %a{ href: '#notifications' } Уведомления
          %li.tab.col.s6
            %a{ href: '#topics' } Подписки

      .col.s12#notifications{ style: 'padding: 0' }
        .card-panel
          = render 'notifications/grid', notifications: @contact.notifications
      .col.s12#topics{ style: 'padding: 0' }
        .card-panel
          = render 'subscribes/grid', subscribes: @contact.subscribes

app/views/contacts/index.html.haml
.section.light-blue{ style: 'min-height: 240px'}

.container{ style: 'margin-top: -150px' }
  .row
    = render 'dashboard/menu'
    .col.s12.m8.l9
      %nav{ style: 'margin-top: 0.5rem' }
        .nav-wrapper
          .col.s12
            = link_to icon('home'), root_path, class: 'breadcrumb'
            = link_to 'Контакты', contacts_path, class: 'breadcrumb'
      .card-panel
        = render 'contacts/grid', contacts: current_user.contacts

app/views/contacts/new.html.haml
.section.light-blue{ style: 'min-height: 240px'}

.container{ style: 'margin-top: -150px'}
  .row
    = render('dashboard/menu')
    .col.s12.m8.l9
      %nav{style: 'margin-top: 0.5rem'}
        .nav-wrapper
          .col.s12
            = link_to icon('home'), root_path, class: 'breadcrumb'
            = link_to 'Контакты', contacts_path, class: 'breadcrumb'
            = link_to 'Добавление', new_contact_path, class: 'breadcrumb'

      .card-panel
        = render 'form', contact: @contact

app/views/contacts/show.html.haml
.section.light-blue{ style: 'min-height: 240px'}

.container{ style: 'margin-top: -150px'}
  .row
    = render('dashboard/menu')
    .col.s12.m8.l9
      %nav{style: 'margin-top: 0.5rem'}
        .nav-wrapper
          .col.s12
            = link_to icon('home'), root_path, class: 'breadcrumb'
            = link_to 'Контакты', contacts_path, class: 'breadcrumb'
            = link_to 'Просмотр', @contact, class: 'breadcrumb'

      .card-panel
        %div
          %p
            = @contact.name
          %p
            = @contact.phone
          %p
            = @contact.token