config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get    'register' => 'devise/registrations#new'
    get    'login'    => 'devise/sessions#new'
    get    'profile'  => 'devise/registrations#edit'
    delete 'logout'   => 'devise/sessions#destroy'
  end

  devise_for :users
  authenticated :user do
    root :to => 'dashboard#index'
  end

  resources :contacts, :notifications, :topics, :events, :subscribe

  # API routes
  scope 'api', as: 'api', defaults: {format: :json} do
    match 'contacts',    to: 'api#contact',     via: :post
    match 'topics',      to: 'api#topics',      via: :get
    match 'events',      to: 'api#events',      via: :get
    # Contact subscribe/unsubscribe for topics
    match 'subscribe',   to: 'api#subscribe',   via: :post
    match 'unsubscribe', to: 'api#unsubscribe', via: :post
  end

  match 'contact', as: 'static_contact', to: 'pages#contact', via: :get
  match 'about',   as: 'static_about',   to: 'pages#about',   via: :get

  root :to => 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :topic
  belongs_to :contact
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  before_action :set_subscribe

  def edit
  end

  def update

  end

  def destroy
    @subscribe.delete
    redirect_to :back, notice: 'Подписка успешно удалена'
  end

  private

  def set_subscribe
    @subscribe = Subscribe.find(params[:id])
  end
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/subscribes/_grid.html.haml
= link_to icon('plus'), new_subscribe_path, class: 'btn-floating btn-large waves-effect waves-light right red', style: 'margin-top: -50px'
- if subscribes.empty?
  %p Еще нет созданных подписок.
- else
  %table.striped
    %thead
      %tr
        %th Тема
        %th Имя
        %th Телефон
        %th Код
    %tbody
      - subscribes.each do |subscribe|
        %tr
          %td= link_to subscribe.topic.title, topic_path(subscribe.topic)
          %td= link_to subscribe.contact.name, contact_path(subscribe.contact)
          %td= subscribe.contact.phone
          %td= subscribe.contact.code
          %td.right
            = link_to icon('pencil'), edit_subscribe_path(subscribe), class: 'btn orange'
            = link_to icon('trash-o'), subscribe_path(subscribe), class: 'btn red', method: :delete, data: { confirm: 'Вы уверены?' }