config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get    'register' => 'devise/registrations#new'
    get    'login'    => 'devise/sessions#new'
    get    'profile'  => 'devise/registrations#edit'
    delete 'logout'   => 'devise/sessions#destroy'
  end

  devise_for :users
  authenticated :user do
    root :to => 'dashboard#index'
  end

  resources :contacts, :notifications, :topics, :events, :subscribe

  # API routes
  scope 'api', as: 'api', defaults: {format: :json} do
    match 'contacts',    to: 'api#contact',     via: :post
    match 'topics',      to: 'api#topics',      via: :get
    match 'events',      to: 'api#events',      via: :get
    # Contact subscribe/unsubscribe for topics
    match 'subscribe',   to: 'api#subscribe',   via: :post
    match 'unsubscribe', to: 'api#unsubscribe', via: :post
  end

  match 'contact', as: 'static_contact', to: 'pages#contact', via: :get
  match 'about',   as: 'static_about',   to: 'pages#about',   via: :get

  root :to => 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :notifications
  has_and_belongs_to_many :topics
  has_many :subscribes

  before_validation :set_contact_code

  validates :name,  presence: true
  validates :phone, presence: true, uniqueness: true
  validates :token, presence: true, uniqueness: true
  validates :code,  presence: true, uniqueness: true, length: { minimum: 9, maximum: 9 }

  private
    def set_contact_code
      if self.code.blank?
        self.code = rand 100000000...999999999
      end
    end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :topic
  delegate :user, :to => :topic
  delegate :contacts, :to => :topic

  validates :title, presence: true
  validates :date, presence: true
  validates :time, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_and_belongs_to_many :contacts
  before_save :send_notification

  validates :text, presence: true
  
  private
    def send_notification
      # if self.topic.contacts
      #   registration_ids = [] # an array of one or more client registration tokens
      #   self.topic.contacts.each do |contact|
      #     registration_ids.push(contact.token)
      #     self.contacts << contact
      #   end

      #   fcm = FCM.new(self.user.token, verify: false)
      #   # you can set option parameters in here
      #   #  - all options are pass to HTTParty method arguments
      #   #  - ref: https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L29-L60
      #   #  fcm = FCM.new("my_api_key", timeout: 3)

      #   options = {notification: {title: self.title, body: self.text, sound: 'default'}, priority: 'high'}
      #   self.response = fcm.send_with_notification_key("topic_#{self.topic_id}", options)[:body]
      # end

      fcm = FCM.new(self.user.token, verify: false)
      options = {notification: {title: self.title, body: self.text, sound: 'default'}, priority: 'high'}
      self.response = fcm.send_with_notification_key("/topics/topic_#{self.topic_id}", options)[:body]
    end
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :topic
  belongs_to :contact
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :events, :dependent => :delete_all
  has_many :subscribes, :dependent => :delete_all
  has_many :notifications, :dependent => :delete_all
  has_many :subscribes, :dependent => :delete_all
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts,      :dependent => :delete_all
  has_many :notifications, :dependent => :delete_all
  has_many :topics,        :dependent => :delete_all
  has_many :events,        :dependent => :delete_all, :through => :topics

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_user
  respond_to :json

  def contact
    @contact = @user.contacts.build
    @contact.name = params[:name]
    @contact.phone = params[:phone]
    @contact.token = params[:token]

    if @contact.save
      render json: { success: true, contact: @contact }
    else
      render json: { success: false, errors: @contact.errors, status: :unprocessable_entity }
    end
  end

  def topics
    render json: { success: true, topics: @user.topics}
  end

  def events
    render json: { success: true, events: @user.events}
  end

  def subscribe
    @contact = Contact.find_by_code(params[:contact])
    if @contact.subscribes.where(topic_id: params[:topic]).any?
      @contact.subscribes.create(topic_id: params[:topic])
      render json: { success: true, message: 'Succefully subscribed'}
    else
      @contact.subscribes.delete(@contact.subscribes.find_by_topic_id(params[:topic]).first)
      render json: { success: true, message: 'Succefully unsubscribed'}
    end
  end

  private
    def set_user
      @user = User.find_by_token(params[:app])
      if @user.nil?
        render json: { success: false, errors: 'Invalid token.'}
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = current_user.events.order(date: :asc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to edit_event_path(@event), notice: 'Событие успешно создано'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to edit_event_path(@event), notice: 'Событие успешно изменено'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to :back, notice: 'Событие успешно удалено'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:topic_id, :title, :description, :date, :time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_footer.html.haml
%footer.page-footer.light-blue
  .container
    .row
      .col.l6.m8.s12
        %h5.white-text Company Bio
        %p.grey-text.text-lighten-4
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque esse labore officiis quis similique?
          Consequatur culpa facere harum ipsa magnam, molestias non numquam quaerat quas vero!
          Corporis explicabo laborum provident.
      .col.l3.m2.s6
        %h5.white-text Links
        %ul
          %li= link_to 'About', static_about_path, class: 'white-text'
          %li= link_to 'Contact', static_contact_path, class: 'white-text'
      .col.l3.m2.s6
        %h5.white-text Connect
        %ul
          %li
            %a.white-text{ href: '#!' } Link 1
          %li
            %a.white-text{ href: '#!' } Link 2
  .footer-copyright
    .container
      Made by
      %a.light-blue-text.text-lighten-3{ href: 'https://github.com/g1nc' } g1nc

app/views/layouts/_header.html.haml
.navbar-fixed
  %nav.light-blue.z-depth-0{ role: 'navigation' }
    .nav-wrapper.container
      = link_to 'Simpletech', root_path, id: 'logo-container', class: 'brand-logo'
      %ul.right.hide-on-med-and-down
        - if user_signed_in?
          %li= link_to icon('user'), profile_path
          %li= link_to icon('hashtag'), topics_path
          %li= link_to icon('calendar'), events_path
          %li= link_to icon('users'), contacts_path
          %li= link_to icon('info'), notifications_path
          %li= link_to icon('sign-out'), logout_path, method: :delete
        - else
          %li= link_to icon('sign-in'), login_path
      %ul.side-nav#nav-mobile
        - if user_signed_in?
          %li= link_to 'Профиль', profile_path
          %li= link_to 'Темы', topics_path
          %li= link_to 'События', events_path
          %li= link_to 'Контакты', contacts_path
          %li= link_to 'Уведомления', notifications_path
          %li= link_to 'Выход', logout_path, method: :delete
        - else
          %li= link_to 'Вход', login_path
      %a.button-collapse{ href:'', data: {:activates => 'nav-mobile'}}= icon('bars')

app/views/layouts/_messages.html.erb
<% if notice %>
    <script type="text/javascript">
      Materialize.toast('<%= notice %>', 4000)
    </script>
<% end %>
<% if alert %>
    <script type="text/javascript">
      Materialize.toast('<%= alert %>', 4000)
    </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Simple Loyalty - Площадка для запуска программы лояльности</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render('layouts/header') %>
    <%= render('layouts/messages') %>
    <main>
      <%= yield %>
    </main>
    <%= render('layouts/footer') %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="section light-blue" style="min-height: 240px"></div>

<div class="container">
  <div class="row">
    <div class="col m10 offset-m1 s12">
      <div class="card-panel" style="margin-top: -150px">
        <div class="row">
          <div class="col m12 l10 offset-l1">
            <h1>Pages#about</h1>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi cum debitis eaque fuga libero minima nesciunt nisi quod suscipit ullam. Officiis porro quis sunt ullam voluptatibus! Delectus optio qui sit.</span><span>Corporis eum libero maxime minima quaerat quidem tenetur totam. Aperiam at aut cupiditate dolore eius et eveniet iusto nemo odio, perspiciatis quis quo similique sunt. Corporis expedita quam ratione vero.</span><span>Consectetur culpa laboriosam necessitatibus neque, nostrum quasi quibusdam quidem velit. Commodi eius est hic ipsam minima nostrum provident, totam voluptatum. Aliquam, aperiam autem doloribus earum mollitia obcaecati pariatur qui veniam?</span>
            </p>
            <p>
              <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores dolor ea eos eum expedita fuga illo inventore, itaque nihil nobis officiis quisquam quo repellat rerum sit tempore vel veniam voluptates.</span><span>Ducimus laudantium maxime quas saepe sed sint veritatis? Distinctio iure porro possimus rem saepe sint ullam. Adipisci aliquam amet blanditiis dicta dolorem dolorum enim eveniet excepturi exercitationem impedit modi, natus?</span><span>Accusantium, ad aspernatur explicabo inventore ipsa libero magnam nam necessitatibus neque perferendis quo ullam, ut voluptate! A consequuntur cum enim eum fugiat illum pariatur quis quos voluptas! Eum laboriosam, voluptas!</span>
            </p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab atque beatae consectetur consequatur deleniti, ea esse fuga illo laboriosam nemo neque nihil odio perferendis quasi ratione rem vero voluptatem voluptatibus.</span><span>Aliquam consectetur cumque enim minus obcaecati sint? Consequatur ea molestiae pariatur. Architecto asperiores autem doloremque earum et, eveniet expedita facilis illo ipsum laboriosam maiores minima reiciendis, rem suscipit tempore unde.</span><span>Accusamus accusantium aliquam architecto atque commodi culpa cupiditate, deleniti dicta, dolores doloribus earum eveniet id illo iure iusto nesciunt nihil nisi obcaecati optio quia ratione repellat rerum tempore totam voluptate!</span>
            </p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto cumque cupiditate ea, eos ex illum ipsa perferendis suscipit vel voluptatibus! Accusamus aliquam at consequuntur libero placeat quaerat reprehenderit rerum soluta.</span><span>Accusamus beatae dolor eius necessitatibus quas quibusdam rem suscipit tenetur? A accusamus blanditiis cupiditate hic iste, labore laudantium minus nulla numquam odio velit voluptatum? Autem eos est nesciunt sequi tempora.</span><span>Dicta eos fugit mollitia nemo, odit omnis provident quasi quidem quis, reprehenderit repudiandae similique, suscipit totam. Accusamus consequuntur corporis dignissimos, eaque excepturi fuga fugit libero provident quae reiciendis voluptas, voluptatum!</span>
            </p>
            <p>
              <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aperiam at blanditiis commodi culpa dolorum explicabo fugit incidunt ipsam mollitia natus, nisi provident quidem unde, velit vero voluptate? Ea, iste.</span><span>Accusamus animi at delectus, ducimus facere impedit inventore omnis! Aperiam ex molestias nam optio sunt ut voluptates. Delectus eaque eos magnam numquam porro. Blanditiis culpa ex id illum molestiae recusandae?</span><span>Accusamus accusantium architecto asperiores, atque blanditiis deleniti doloremque dolores eaque enim eos esse magni necessitatibus nemo non, placeat provident quis, sequi sit tenetur unde! Consequuntur harum necessitatibus quae quos veritatis!</span>
            </p>
            <p>
              <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur dolorum est, eveniet ex iusto nobis officia officiis omnis placeat provident quia quis ratione reiciendis repellendus reprehenderit sed similique sit veritatis?</span><span>A alias aliquid animi architecto blanditiis cumque dolorem et, harum modi nisi nulla perferendis provident, quibusdam reiciendis repudiandae tempora ullam voluptas voluptates. A ad explicabo facere necessitatibus quaerat quo voluptate!</span><span>Aliquam autem cum deleniti distinctio doloribus facere laudantium libero maiores maxime minus neque nobis quod reiciendis repudiandae rerum sapiente, veniam? Animi corporis nostrum praesentium quaerat reiciendis rem rerum, sint ut?</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="section light-blue" style="min-height: 240px"></div>

<div class="container">
  <div class="row">
    <div class="col m10 offset-m1 s12">
      <div class="card-panel" style="margin-top: -150px">
        <div class="row">
          <div class="col m12 l10 offset-l1">
            <h1>Pages#contact</h1>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi cum debitis eaque fuga libero minima nesciunt nisi quod suscipit ullam. Officiis porro quis sunt ullam voluptatibus! Delectus optio qui sit.</span><span>Corporis eum libero maxime minima quaerat quidem tenetur totam. Aperiam at aut cupiditate dolore eius et eveniet iusto nemo odio, perspiciatis quis quo similique sunt. Corporis expedita quam ratione vero.</span><span>Consectetur culpa laboriosam necessitatibus neque, nostrum quasi quibusdam quidem velit. Commodi eius est hic ipsam minima nostrum provident, totam voluptatum. Aliquam, aperiam autem doloribus earum mollitia obcaecati pariatur qui veniam?</span>
            </p>
            <p>
              <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores dolor ea eos eum expedita fuga illo inventore, itaque nihil nobis officiis quisquam quo repellat rerum sit tempore vel veniam voluptates.</span><span>Ducimus laudantium maxime quas saepe sed sint veritatis? Distinctio iure porro possimus rem saepe sint ullam. Adipisci aliquam amet blanditiis dicta dolorem dolorum enim eveniet excepturi exercitationem impedit modi, natus?</span><span>Accusantium, ad aspernatur explicabo inventore ipsa libero magnam nam necessitatibus neque perferendis quo ullam, ut voluptate! A consequuntur cum enim eum fugiat illum pariatur quis quos voluptas! Eum laboriosam, voluptas!</span>
            </p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab atque beatae consectetur consequatur deleniti, ea esse fuga illo laboriosam nemo neque nihil odio perferendis quasi ratione rem vero voluptatem voluptatibus.</span><span>Aliquam consectetur cumque enim minus obcaecati sint? Consequatur ea molestiae pariatur. Architecto asperiores autem doloremque earum et, eveniet expedita facilis illo ipsum laboriosam maiores minima reiciendis, rem suscipit tempore unde.</span><span>Accusamus accusantium aliquam architecto atque commodi culpa cupiditate, deleniti dicta, dolores doloribus earum eveniet id illo iure iusto nesciunt nihil nisi obcaecati optio quia ratione repellat rerum tempore totam voluptate!</span>
            </p>
            <p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto cumque cupiditate ea, eos ex illum ipsa perferendis suscipit vel voluptatibus! Accusamus aliquam at consequuntur libero placeat quaerat reprehenderit rerum soluta.</span><span>Accusamus beatae dolor eius necessitatibus quas quibusdam rem suscipit tenetur? A accusamus blanditiis cupiditate hic iste, labore laudantium minus nulla numquam odio velit voluptatum? Autem eos est nesciunt sequi tempora.</span><span>Dicta eos fugit mollitia nemo, odit omnis provident quasi quidem quis, reprehenderit repudiandae similique, suscipit totam. Accusamus consequuntur corporis dignissimos, eaque excepturi fuga fugit libero provident quae reiciendis voluptas, voluptatum!</span>
            </p>
            <p>
              <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aperiam at blanditiis commodi culpa dolorum explicabo fugit incidunt ipsam mollitia natus, nisi provident quidem unde, velit vero voluptate? Ea, iste.</span><span>Accusamus animi at delectus, ducimus facere impedit inventore omnis! Aperiam ex molestias nam optio sunt ut voluptates. Delectus eaque eos magnam numquam porro. Blanditiis culpa ex id illum molestiae recusandae?</span><span>Accusamus accusantium architecto asperiores, atque blanditiis deleniti doloremque dolores eaque enim eos esse magni necessitatibus nemo non, placeat provident quis, sequi sit tenetur unde! Consequuntur harum necessitatibus quae quos veritatis!</span>
            </p>
            <p>
              <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur dolorum est, eveniet ex iusto nobis officia officiis omnis placeat provident quia quis ratione reiciendis repellendus reprehenderit sed similique sit veritatis?</span><span>A alias aliquid animi architecto blanditiis cumque dolorem et, harum modi nisi nulla perferendis provident, quibusdam reiciendis repudiandae tempora ullam voluptas voluptates. A ad explicabo facere necessitatibus quaerat quo voluptate!</span><span>Aliquam autem cum deleniti distinctio doloribus facere laudantium libero maiores maxime minus neque nobis quod reiciendis repudiandae rerum sapiente, veniam? Animi corporis nostrum praesentium quaerat reiciendis rem rerum, sint ut?</span>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="section no-pad-bot light-blue" id="index-banner" style="min-height: 93vh">
  <div class="hero">
    <h1 class="header center white-text">Simple Loyalty</h1>
    <div class="row center">
      <h5 class="header col s12 white-text light">Площадка для запуска программы лояльности</h5>
    </div>
    <div class="row center">
      <%= link_to 'Начать', login_path, class: 'btn-large waves-effect waves-light orange' %>
    </div>
    <div class="row">
      <%= link_to icon('chevron-down'), '#!', class: 'btn-flat waves-effect waves-light white-text scroll-to btn-floating btn-large', data: { to: '#features'}  %>
    </div>
  </div>
</div>

<div class="container">
  <div class="section" id="features">
    <div class="row"></div>

    <div class="row">
      <div class="col l5 m12">
        <blockquote>
          <h4>Web-cервис</h4>
          <h5>Рабочее место маркетолога</h5>
        </blockquote>
        <ul class="collection features">
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Планирование и проведение маркетинговых кампаний</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Настройка параметров компании</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Создание персонализированных Push-уведомлений</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Массовые уведомления (приглашения на сезонные скидки, мероприятия, промо-акции)</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Автоматические точечные уведомления (предоставление скидки в день рождения)</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Учет и ведение клиентских данных</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Возможность модернизации до корпоративной CRM системы</li>
        </ul>
      </div>
      <div class="col l7 m12 center">
        <%= image_tag('web-application.png', :class => 'responsive-img') %>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div class="divider"></div>
      </div>
    </div>

    <div class="row">
      <div class="col l7 m12 center">
        <%= image_tag('mobile-application.png', :class => 'responsive-img') %>
      </div>
      <div class="col l5 m12">
        <blockquote>
          <h4>Мобильное приложение</h4>
        </blockquote>
        <ul class="collection features">
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Цифровая карта лояльности - универсальна и всегда при себе</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Настройка параметров компанииПолучение контактных данных клиентов и потенциальных клиентов, при первом запуске приложения</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Возможность загрузки приложения через Google Play или QR-код</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Отображение Push-уведомлений</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Возможноть импорта и показа промо изображений</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Возможность модернизации до кроссплатформенного многофункционального приложения</li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div class="divider"></div>
      </div>
    </div>

    <div class="row">
      <div class="col l5 m12">
        <blockquote>
          <h4>Адаптация 1С</h4>
        </blockquote>
        <ul class="collection features">
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Настройка интеграции с веб-кабинетом маркетолога</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Настройка функционала для группировки и фиксации временных скидок по выбранным позициям/категориям</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>Точечная настройка механики учета скидок с использованием цифровой карты</li>
          <li class="collection-item"><%= icon('circle-thin', class: 'left') %>В зависимости от конфигурации и версии 1С могут потребоваться дополнительные настройки</li>

        </ul>
      </div>
      <div class="col l7 m12 center">
        <%= image_tag('notebook-application.png', :class => 'responsive-img') %>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <div class="divider"></div>
      </div>
    </div>

    <div class="row">
      <div class="col l4 m12 center">
        <%= image_tag 'icons/cog.png' %>
        <h5>Легкая интеграция c Вашей системой</h5>
      </div>
      <div class="col l4 m12 center">
        <%= image_tag 'icons/gift.png' %>
        <h5>Мобильный телефон вместо карты</h5>
      </div>
      <div class="col l4 m12 center">
        <%= image_tag 'icons/comment.png' %>
        <h5>Канал коммуникации с клиентом</h5>
      </div>
    </div>
  </div>
</div>